### ISSUE TITLE
vfs: don't call 'handle_io_response()' in regular VFS functions

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2896]
Calling `handle_io_response()` in a regular VFS function (in contrast to a post-signal hook) can cause problems if the caller of the VFS function holds a lock which prevents the io response handler from returning.

Currently, the `File_system` VFS plugin calls `handle_io_response()` in `complete_read()` and `complete_sync()` to wake up anyone who might be blocking after a failed `queue_read()`, `queue_sync()` or `write()` call. It would probably be better to leave this unblocking step to the user of the VFS.

The test in [1] triggers the problem. In an example run, the main thread dispatched an io signal and waited for the select callback list lock, thread 1 had the select callback list lock and waited for the libc VFS lock and thread 2 had the libc VFS lock and waited for the select callback list lock (via the `handle_io_response()` call from `complete_read()`)

```
main thread

#0  pseudo_end () at /.../repos/base-linux/src/lib/syscall/spec/x86_64/lx_syscall.S:29
#1  0x00007f44c63fff31 in lx_futex (val=0, op=0, uaddr=<optimized out>) at /.../repos/base-linux/src/lib/syscall/linux_syscalls.h:350
#2  thread_stop_myself () at /.../repos/base-linux/src/include/base/internal/lock_helper.h:63
#3  Genode::Cancelable_lock::lock (this=this@entry=0x11692c0 <select_cb_list>) at /.../repos/base/src/lib/base/lock.cc:123
#4  0x00000000010e8754 in Genode::Lock::lock (this=0x11692c0 <select_cb_list>) at /.../repos/base/include/base/lock.h:33
#5  Genode::Lock_guard<Genode::Lock>::Lock_guard (lock=..., this=<synthetic pointer>) at /.../repos/base/include/base/lock_guard.h:40
#6  Libc::Select_cb_list::Guard::Guard (list=..., this=<synthetic pointer>) at /.../repos/libports/src/lib/libc/select.cc:74
#7  Libc::Select_cb_list::for_each<select_notify()::<lambda(Libc::Select_cb&)> > (this=0x11692c0 <select_cb_list>, func=...) at /.../repos/libports/src/lib/libc/select.cc:105
#8  select_notify () at /.../repos/libports/src/lib/libc/select.cc:197
#9  0x00000000010fea23 in Libc::Io_response_handler::handle_io_response (this=<optimized out>) at /.../repos/libports/src/lib/libc/task.cc:395
#10 0x0000000001199c47 in Vfs::Fs_file_system::Post_signal_hook::function (this=0x7f44ce391680) at /.../repos/os/src/lib/vfs/fs_file_system.h:459
#11 0x00007f44c63f5cb9 in Genode::Entrypoint::_execute_post_signal_hook (this=0x7f44c64959a0 <Genode::bootstrap_component()::startup+352>) at /.../repos/base/include/base/entrypoint.h:102
#12 Genode::Entrypoint::_wait_and_dispatch_one_io_signal (this=0x7f44c64959a0 <Genode::bootstrap_component()::startup+352>, dont_block=dont_block@entry=false) at /.../repos/base/src/lib/base/entrypoint.cc:212
#13 0x0000000001106bb9 in Genode::Entrypoint::wait_and_dispatch_one_io_signal (this=<optimized out>) at /.../repos/base/include/base/entrypoint.h:190
#14 Libc::Kernel::run (this=0x1169320 <Libc::Kernel* unmanaged_singleton<Libc::Kernel, 8, Genode::Env&, Genode::Allocator&>(Genode::Env&, Genode::Allocator&)::object_space>, app_code=...) at /.../repos/libports/src/lib/libc/task.cc:676
#15 0x0000000001106d56 in Libc::execute_in_application_context (app_code=...) at /.../repos/libports/src/lib/libc/task.cc:949
#16 0x000000000120570c in Libc::with_libc<Libc::Component::construct(Libc::Env&)::<lambda()> > (func=...) at /.../repos/libports/include/libc/component.h:134
#17 Libc::Component::construct (env=...) at /.../repos/libports/src/lib/posix/construct.cc:112
#18 0x00000000011080fa in Component::construct (env=...) at /.../repos/libports/src/lib/libc/task.cc:1001
#19 0x00007f44c6464196 in Linker::Binary::call_entry_point (env=..., this=0x7f44c655d190 <Linker::Binary* unmanaged_singleton<Linker::Binary, 8, Genode::Env&, Genode::Heap&, Linker::Bind>(Genode::Env&, Genode::Heap&, Linker::Bind&&)::object_space>) at /.../repos/base/src/lib/ldso/main.cc:421
#20 Component::construct (env=...) at /.../repos/base/src/lib/ldso/main.cc:720
#21 0x00007f44c63f6dfe in (anonymous namespace)::Constructor_component::construct (this=0x7f44ce4ffc70) at /.../repos/base/src/lib/base/entrypoint.cc:292
#22 Genode::Meta::call_member<Genode::Meta::Empty, (anonymous namespace)::Constructor_component, Genode::Meta::Empty> (func=<optimized out>, server=...) at /.../repos/base/include/util/meta.h:464
#23 (anonymous namespace)::Constructor::Rpc_construct::serve<(anonymous namespace)::Constructor_component, Genode::Meta::Empty> (args=<synthetic pointer>, server=...) at /.../repos/base/src/lib/base/entrypoint.cc:272
#24 Genode::Rpc_dispatcher<(anonymous namespace)::Constructor, (anonymous namespace)::Constructor_component>::_do_serve<(anonymous namespace)::Constructor::Rpc_construct> (args=<synthetic pointer>, this=0x7f44ce4ffcf8) at /.../repos/base/include/base/rpc_server.h:146
#25 Genode::Rpc_dispatcher<(anonymous namespace)::Constructor, (anonymous namespace)::Constructor_component>::_do_dispatch<Genode::Meta::Type_list<(anonymous namespace)::Constructor::Rpc_construct> > (in=..., out=..., opcode=..., this=0x7f44ce4ffcf8) at /.../repos/base/include/base/rpc_server.h:180
#26 Genode::Rpc_dispatcher<(anonymous namespace)::Constructor, (anonymous namespace)::Constructor_component>::dispatch (in=..., out=..., opcode=..., this=0x7f44ce4ffcf8) at /.../repos/base/include/base/rpc_server.h:235
#27 Genode::Rpc_object<(anonymous namespace)::Constructor, (anonymous namespace)::Constructor_component>::dispatch (this=0x7f44ce4ffc70, opcode=..., in=..., out=...) at /.../repos/base/include/base/rpc_server.h:272
#28 0x00007f44c641384f in Genode::Rpc_entrypoint::<lambda(Genode::Rpc_object_base*)>::operator() (obj=0x7f44ce4ffc70, __closure=<synthetic pointer>) at /.../repos/base/src/lib/base/rpc_dispatch_loop.cc:80
#29 Genode::Object_pool<Genode::Rpc_object_base>::apply<Genode::Rpc_entrypoint::entry()::<lambda(Genode::Rpc_object_base*)> > (func=..., capid=<optimized out>, this=0x7f44c6495a50 <Genode::bootstrap_component()::startup+528>) at /.../repos/base/include/base/object_pool.h:146
#30 Genode::Rpc_entrypoint::entry (this=0x7f44c64959a8 <Genode::bootstrap_component()::startup+360>) at /.../repos/base/src/lib/base/rpc_dispatch_loop.cc:82
#31 0x00007f44c643e8ee in Genode::Thread::_thread_start () at /.../repos/base-linux/src/lib/base/thread_linux.cc:79
#32 0x00007f44c64530fd in thread_start () at /.../repos/base-linux/src/lib/syscall/spec/x86_64/lx_clone.S:62
```

```
thread 1

#0  pseudo_end () at /.../repos/base-linux/src/lib/syscall/spec/x86_64/lx_syscall.S:29
#1  0x00007f44c63fff31 in lx_futex (val=0, op=0, uaddr=<optimized out>) at /.../repos/base-linux/src/lib/syscall/linux_syscalls.h:350
#2  thread_stop_myself () at /.../repos/base-linux/src/include/base/internal/lock_helper.h:63
#3  Genode::Cancelable_lock::lock (this=this@entry=0x116c540 <vfs_lock()::_vfs_lock>) at /.../repos/base/src/lib/base/lock.cc:123
#4  0x000000000110dbf8 in Genode::Lock::lock (this=<optimized out>) at /.../repos/base/include/base/lock.h:33
#5  Genode::Lock_guard<Genode::Lock>::Lock_guard (lock=..., this=<synthetic pointer>) at /.../repos/base/include/base/lock_guard.h:40
#6  Libc::notify_read_ready (handle=handle@entry=0x7f44ce39a570) at /.../repos/libports/src/lib/libc/vfs_plugin.cc:168
#7  0x000000000110e022 in Libc::Vfs_plugin::select (this=0x11695a0 <Libc::Kernel* unmanaged_singleton<Libc::Kernel, 8, Genode::Env&, Genode::Allocator&>(Genode::Env&, Genode::Allocator&)::object_space+640>, nfds=<optimized out>, readfds=0x7f44ce8ff750, writefds=0x7f44ce8ff7d0, exceptfds=<optimized out>, timeout=<optimized out>) at /.../repos/libports/src/lib/libc/vfs_plugin.cc:1246
#8  0x00000000010e8513 in selscan (nfds=nfds@entry=9, in_readfds=in_readfds@entry=0x7f44ce8ff990, in_writefds=in_writefds@entry=0x7f44ce8ffa10, in_exceptfds=in_exceptfds@entry=0x7f44ce8ffa90, out_readfds=out_readfds@entry=0x7f44ce8ffd40, out_writefds=out_writefds@entry=0x0, out_exceptfds=<optimized out>) at /.../repos/libports/src/lib/libc/select.cc:152
#9  0x00000000010e8e57 in _select (nfds=9, readfds=readfds@entry=0x7f44ce8ffd40, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, tv=tv@entry=0x7f44ce8ffd30) at /.../repos/libports/src/lib/libc/select.cc:244
#10 0x00000000010e97a8 in select (nfds=<optimized out>, readfds=readfds@entry=0x7f44ce8ffd40, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7f44ce8ffd30) at /.../repos/libports/src/lib/libc/select.cc:307
#11 0x0000000001000264 in thread1_func () at /.../repos/libports/src/test/libc_vfs_lock_select_lock/main.cc:44
#12 0x0000000001215d71 in pthread::Thread_object::entry (this=0x7f44ce397248) at /.../repos/libports/src/lib/pthread/thread.cc:58
#13 0x00007f44c643e8ee in Genode::Thread::_thread_start () at /.../repos/base-linux/src/lib/base/thread_linux.cc:79
#14 0x00007f44c64530fd in thread_start () at /.../repos/base-linux/src/lib/syscall/spec/x86_64/lx_clone.S:62
```

```
thread 2

#0  pseudo_end () at /.../repos/base-linux/src/lib/syscall/spec/x86_64/lx_syscall.S:29
#1  0x00007f44c63fff31 in lx_futex (val=0, op=0, uaddr=<optimized out>) at /.../repos/base-linux/src/lib/syscall/linux_syscalls.h:350
#2  thread_stop_myself () at /.../repos/base-linux/src/include/base/internal/lock_helper.h:63
#3  Genode::Cancelable_lock::lock (this=this@entry=0x11692c0 <select_cb_list>) at /.../repos/base/src/lib/base/lock.cc:123
#4  0x00000000010e8754 in Genode::Lock::lock (this=0x11692c0 <select_cb_list>) at /.../repos/base/include/base/lock.h:33
#5  Genode::Lock_guard<Genode::Lock>::Lock_guard (lock=..., this=<synthetic pointer>) at /.../repos/base/include/base/lock_guard.h:40
#6  Libc::Select_cb_list::Guard::Guard (list=..., this=<synthetic pointer>) at /.../repos/libports/src/lib/libc/select.cc:74
#7  Libc::Select_cb_list::for_each<select_notify()::<lambda(Libc::Select_cb&)> > (this=0x11692c0 <select_cb_list>, func=...) at /.../repos/libports/src/lib/libc/select.cc:105
#8  select_notify () at /.../repos/libports/src/lib/libc/select.cc:197
#9  0x00000000010fea23 in Libc::Io_response_handler::handle_io_response (this=<optimized out>) at /.../repos/libports/src/lib/libc/task.cc:395
#10 0x00000000011a028c in Vfs::Fs_file_system::Fs_vfs_handle::_complete_read (this=0x7f44ce39a570, dst=<optimized out>, count=<optimized out>, out_count=@0x7f44ce9ffcf8: 1) at /.../repos/os/src/lib/vfs/fs_file_system.h:147
#11 0x0000000001199808 in Vfs::Fs_file_system::complete_read (this=0x7f44ce38f000, vfs_handle=0x7f44ce39a570, dst=0x7f44ce9ffdbf "", count=1, out_count=@0x7f44ce9ffcf8: 1) at /.../repos/os/src/lib/vfs/fs_file_system.h:1009
#12 0x000000000110aabb in Libc::Vfs_plugin::Check::suspend (this=0x7f44ce9ffd00) at /.../repos/libports/src/lib/libc/vfs_plugin.cc:540
#13 0x0000000001107782 in Libc::Pthreads::suspend_myself (timeout_ms=<optimized out>, check=..., this=0x1169ce8 <Libc::Kernel* unmanaged_singleton<Libc::Kernel, 8, Genode::Env&, Genode::Allocator&>(Genode::Env&, Genode::Allocator&)::object_space+2504>) at /.../repos/libports/src/lib/libc/task.cc:367
#14 Libc::Kernel::suspend (timeout_ms=<optimized out>, check=..., this=0x1169320 <Libc::Kernel* unmanaged_singleton<Libc::Kernel, 8, Genode::Env&, Genode::Allocator&>(Genode::Env&, Genode::Allocator&)::object_space>) at /.../repos/libports/src/lib/libc/task.cc:735
#15 Libc::suspend (s=..., timeout_ms=timeout_ms@entry=0) at /.../repos/libports/src/lib/libc/task.cc:882
#16 0x000000000110e29b in Libc::Vfs_plugin::read (this=<optimized out>, fd=<optimized out>, buf=0x7f44ce9ffdbf, count=1) at /.../repos/libports/src/lib/libc/vfs_plugin.cc:551
#17 0x00000000010000df in thread2_func () at /.../repos/libports/src/test/libc_vfs_lock_select_lock/main.cc:28
```

[1] https://github.com/cproc/genode/commit/b2ab3b4ebd61f32e84d8325e9cd8338861730a7f

Related to #2635

**Comment by cproc** [comment]
Marked as fixed.
